# Generated by Django 5.2.17 on 2026-09-14 19:56

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import tracker.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=tracker.models.id_it,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sku", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=160)),
                ("category", models.CharField(max_length=20)),
                ("unit", models.CharField(default="pcs", max_length=10)),
                ("is_serialised", models.BooleanField(default=False)),
                (
                    "reorder_level",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "reorder_qty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("make", models.CharField(blank=True, max_length=80, null=True)),
                ("model", models.CharField(blank=True, max_length=120, null=True)),
                ("warranty_months", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "code",
                    models.CharField(max_length=24, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "is_global",
                    models.BooleanField(
                        default=False,
                        help_text="Applies to every project without a membership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=tracker.models.id_v,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("category", models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        default=tracker.models.id_u,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True, related_name="users", to="tracker.role"
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=tracker.models.id_ap,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField()),
                ("required_roles", models.JSONField(default=list)),
                ("decisions", models.JSONField(default=list)),
                ("status", models.CharField(default="pending", max_length=10)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "target_stage",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "id",
                    models.CharField(
                        default=tracker.models.id_p,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("client_name", models.CharField(max_length=120)),
                ("branch_name", models.CharField(max_length=120)),
                ("location", models.CharField(max_length=160)),
                ("project_type", models.CharField(max_length=20)),
                (
                    "system_capacity_kwp",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("stage", models.PositiveSmallIntegerField(default=0)),
                ("rag", models.CharField(default="green", max_length=6)),
                ("rag_reason", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "contract_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "approved_budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "committed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "actual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("stage_planned", models.JSONField(blank=True, default=dict)),
                ("stage_actual", models.JSONField(blank=True, default=dict)),
                ("defects_liability_end", models.DateField(blank=True, null=True)),
                (
                    "retention_percent",
                    models.DecimalField(decimal_places=2, default=5, max_digits=5),
                ),
                (
                    "wyre_investor_project_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Link to investors_project in the Wyre backend (optional)",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead_engineer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GoodsReceipt",
            fields=[
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("checked", "Checked"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField()),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("check_comment", models.TextField(blank=True, null=True)),
                ("review_version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.CharField(
                        default=tracker.models.id_grn,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("grn_number", models.CharField(max_length=30)),
                ("received_at", models.DateTimeField()),
                ("lines", models.JSONField(default=list)),
                ("attachment_ids", models.JSONField(default=list)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipts",
                        to="tracker.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("checked", "Checked"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField()),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("check_comment", models.TextField(blank=True, null=True)),
                ("review_version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.CharField(
                        default=tracker.models.id_doc,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("doc_type", models.CharField(max_length=30)),
                ("title", models.CharField(max_length=200)),
                ("status", models.CharField(default="submitted", max_length=10)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateField(blank=True, null=True)),
                ("issuer", models.CharField(blank=True, max_length=120, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("file_name", models.CharField(max_length=200)),
                ("size_bytes", models.BigIntegerField(default=0)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="documents/%Y/%m/"
                    ),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="tracker.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CostItem",
            fields=[
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("checked", "Checked"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField()),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("check_comment", models.TextField(blank=True, null=True)),
                ("review_version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.CharField(
                        default=tracker.models.id_ci,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("category", models.CharField(max_length=20)),
                ("label", models.CharField(max_length=200)),
                (
                    "planned_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_items",
                        to="tracker.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CommissioningRecord",
            fields=[
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("checked", "Checked"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField()),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("check_comment", models.TextField(blank=True, null=True)),
                ("review_version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.CharField(
                        default=tracker.models.id_com,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("station_id", models.CharField(blank=True, max_length=40, null=True)),
                ("date", models.DateField()),
                ("result", models.CharField(max_length=12)),
                ("notes", models.TextField(blank=True)),
                ("items", models.JSONField(default=list)),
                ("meter", models.JSONField(default=dict)),
                ("client_witness", models.JSONField(blank=True, null=True)),
                ("attachment_ids", models.JSONField(default=list)),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "engineer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commissionings",
                        to="tracker.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChronologyEvent",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=tracker.models.id_ev,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("event_type", models.CharField(max_length=30)),
                ("summary", models.CharField(max_length=400)),
                ("detail", models.TextField(blank=True, null=True)),
                ("ref", models.JSONField(blank=True, null=True)),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="tracker.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChangeOrder",
            fields=[
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "id",
                    models.CharField(
                        default=tracker.models.id_co,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("co_number", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=200)),
                ("reason", models.TextField()),
                ("scope_delta", models.TextField(blank=True)),
                (
                    "cost_delta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("time_delta_days", models.IntegerField(default=0)),
                ("status", models.CharField(default="pending_approval", max_length=20)),
                (
                    "approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tracker.approval",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="change_orders",
                        to="tracker.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("checked", "Checked"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField()),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("check_comment", models.TextField(blank=True, null=True)),
                ("review_version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.CharField(
                        default=tracker.models.id_att,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_name", models.CharField(max_length=200)),
                ("mime", models.CharField(default="image/jpeg", max_length=80)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("kind", models.CharField(default="image", max_length=10)),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("gps", models.JSONField(blank=True, null=True)),
                ("sha256", models.CharField(max_length=64)),
                ("uploaded_at", models.DateTimeField()),
                ("linked_to", models.JSONField(blank=True, null=True)),
                ("caption", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="attachments/%Y/%m/"
                    ),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachments",
                        to="tracker.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="approval",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approvals",
                to="tracker.project",
            ),
        ),
        migrations.CreateModel(
            name="ProjectMembership",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=tracker.models.id_m,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role", models.CharField(max_length=24)),
                ("granted_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tracker.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=tracker.models.id_pi,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("description", models.CharField(max_length=200)),
                ("qty", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=18)),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "qty_received",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cost_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tracker.costitem",
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tracker.inventoryitem",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "id",
                    models.CharField(
                        default=tracker.models.id_as,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("asset_type", models.CharField(max_length=12)),
                ("make", models.CharField(blank=True, max_length=80)),
                ("model", models.CharField(blank=True, max_length=120)),
                ("serial", models.CharField(max_length=80, unique=True)),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("install_date", models.DateTimeField(blank=True, null=True)),
                (
                    "location_on_site",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("warranty_start", models.DateField(blank=True, null=True)),
                ("warranty_end", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="in_stock", max_length=16)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tracker.goodsreceipt",
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="tracker.inventoryitem",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="tracker.project",
                    ),
                ),
                (
                    "purchase_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tracker.purchaseitem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "id",
                    models.CharField(
                        default=tracker.models.id_po,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("po_number", models.CharField(max_length=30)),
                ("status", models.CharField(default="pending_approval", max_length=20)),
                ("raised_at", models.DateTimeField()),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tracker.approval",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="tracker.project",
                    ),
                ),
                (
                    "raised_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tracker.vendor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="po",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="tracker.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="po",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="goods_receipts",
                to="tracker.purchaseorder",
            ),
        ),
        migrations.CreateModel(
            name="QbBill",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=tracker.models.id_qb,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("doc_number", models.CharField(max_length=60)),
                ("vendor_name", models.CharField(max_length=160)),
                ("txn_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("currency", models.CharField(default="NGN", max_length=5)),
                ("match_status", models.CharField(default="unmatched", max_length=10)),
                ("synced_at", models.DateTimeField()),
                (
                    "matched_po",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tracker.purchaseorder",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qb_bills",
                        to="tracker.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SiteVisit",
            fields=[
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("checked", "Checked"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField()),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("check_comment", models.TextField(blank=True, null=True)),
                ("review_version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.CharField(
                        default=tracker.models.id_vis,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("station_id", models.CharField(blank=True, max_length=40, null=True)),
                ("visit_type", models.CharField(max_length=16)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField()),
                ("technician_ids", models.JSONField(default=list)),
                (
                    "duration_hrs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("findings", models.TextField()),
                ("actions_taken", models.TextField(blank=True)),
                (
                    "cost_travel",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "cost_labour",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "cost_parts",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "cost_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("parts", models.JSONField(default=list)),
                ("attachment_ids", models.JSONField(default=list)),
                ("issue_ids", models.JSONField(default=list)),
                ("client_signoff", models.JSONField(blank=True, null=True)),
                ("gps", models.JSONField(blank=True, null=True)),
                ("offline_captured_at", models.DateTimeField(blank=True, null=True)),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to="tracker.project",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("checked", "Checked"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField()),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("check_comment", models.TextField(blank=True, null=True)),
                ("review_version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.CharField(
                        default=tracker.models.id_iss,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("station_id", models.CharField(blank=True, max_length=40, null=True)),
                ("category", models.CharField(max_length=16)),
                ("severity", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("raised_at", models.DateTimeField()),
                ("source", models.CharField(default="manual", max_length=20)),
                ("status", models.CharField(default="open", max_length=16)),
                ("root_cause", models.TextField(blank=True, null=True)),
                ("resolution", models.TextField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cost_to_resolve",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "warranty_claim_id",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("before_attachment_ids", models.JSONField(default=list)),
                ("after_attachment_ids", models.JSONField(default=list)),
                ("is_snag", models.BooleanField(default=False)),
                ("sla_due_at", models.DateTimeField()),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issues",
                        to="tracker.asset",
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "raised_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issues",
                        to="tracker.project",
                    ),
                ),
                (
                    "linked_visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tracker.sitevisit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HseIncident",
            fields=[
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("checked", "Checked"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField()),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("check_comment", models.TextField(blank=True, null=True)),
                ("review_version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.CharField(
                        default=tracker.models.id_hse,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("type", models.CharField(max_length=16)),
                ("severity", models.CharField(max_length=10)),
                ("description", models.TextField()),
                ("actions", models.TextField(blank=True)),
                ("occurred_at", models.DateTimeField()),
                ("attachment_ids", models.JSONField(default=list)),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hse_incidents",
                        to="tracker.project",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tracker.sitevisit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StockLocation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=tracker.models.id_loc,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("type", models.CharField(max_length=12)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "custodian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockCount",
            fields=[
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "id",
                    models.CharField(
                        default=tracker.models.id_sc,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("count_date", models.DateField()),
                ("status", models.CharField(default="open", max_length=10)),
                ("lines", models.JSONField(default=list)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "variance_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tracker.approval",
                    ),
                ),
                (
                    "counted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tracker.stocklocation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="sitevisit",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tracker.stocklocation",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tracker.stocklocation",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="tracker.stocklocation",
            ),
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("checked", "Checked"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField()),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("check_comment", models.TextField(blank=True, null=True)),
                ("review_version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.CharField(
                        default=tracker.models.id_mv,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("movement_type", models.CharField(max_length=12)),
                ("qty", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("source_ref", models.JSONField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("serials", models.JSONField(blank=True, null=True)),
                ("attachment_ids", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(db_index=True)),
                (
                    "approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tracker.approval",
                    ),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="tracker.inventoryitem",
                    ),
                ),
                (
                    "location_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tracker.stocklocation",
                    ),
                ),
                (
                    "location_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tracker.stocklocation",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="tracker.project",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Threshold",
            fields=[
                (
                    "key",
                    models.CharField(max_length=60, primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=120)),
                ("value", models.CharField(max_length=60)),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("effective_from", models.DateField()),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="default_vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="tracker.vendor",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="tracker.vendor",
            ),
        ),
        migrations.CreateModel(
            name="Actual",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=tracker.models.id_act,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("category", models.CharField(max_length=20)),
                ("source", models.CharField(max_length=20)),
                ("source_ref", models.JSONField(default=dict)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("date", models.DateTimeField()),
                ("attachment_ids", models.JSONField(default=list)),
                ("qb_bill_id", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cost_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tracker.costitem",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actuals",
                        to="tracker.project",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tracker.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WarrantyClaim",
            fields=[
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("checked", "Checked"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField()),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("check_comment", models.TextField(blank=True, null=True)),
                ("review_version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.CharField(
                        default=tracker.models.id_war,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("claimed_at", models.DateTimeField()),
                ("status", models.CharField(default="raised", max_length=10)),
                ("outcome", models.TextField(blank=True, null=True)),
                (
                    "cost_recovered",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warranty_claims",
                        to="tracker.asset",
                    ),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tracker.issue",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warranty_claims",
                        to="tracker.project",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tracker.vendor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Retention",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="retention",
                        serialize=False,
                        to="tracker.project",
                    ),
                ),
                ("percent", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "amount_held",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("release_conditions", models.CharField(blank=True, max_length=300)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tracker.approval",
                    ),
                ),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("permission", models.CharField(max_length=40)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="tracker.role",
                    ),
                ),
            ],
            options={
                "unique_together": {("role", "permission")},
            },
        ),
    ]
