# Generated by Django 5.2.17 on 2026-09-14 23:56

import tracker.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=tracker.storage.attachment_path
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=tracker.storage.document_path
            ),
        ),
    ]
