# Generated by Django 5.2.17 on 2026-09-15 21:58

import django.db.models.deletion
import tracker.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_document_sha256_alter_attachment_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=tracker.models.id_ntf,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=32)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.CharField(blank=True, max_length=400)),
                ("link", models.CharField(blank=True, max_length=200)),
                ("ref", models.JSONField(blank=True, null=True)),
                ("dedupe_key", models.CharField(max_length=160)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="tracker.project",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "read_at"],
                        name="tracker_not_recipie_18cb00_idx",
                    )
                ],
                "unique_together": {("recipient", "dedupe_key")},
            },
        ),
    ]
