# Generated by Django 5.2.17 on 2026-09-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="emailed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
