# Generated by Django 5.2.17 on 2026-09-20 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_consolidate_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='commissioning_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
