# Generated by Django 5.2.17 on 2026-09-20 02:01

import django.db.models.deletion
import tracker.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_project_commissioning_assignee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.CharField(default=tracker.models.id_ext, max_length=40, primary_key=True, serialize=False)),
                ('source_kind', models.CharField(max_length=12)),
                ('source_id', models.CharField(max_length=40)),
                ('target', models.CharField(default='document_meta', max_length=24)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='queued', max_length=10)),
                ('transcript', models.TextField(blank=True)),
                ('fields', models.JSONField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, max_length=60)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('error', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='tracker.project')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'requested_at'], name='tracker_ext_status_00f1e8_idx')],
            },
        ),
    ]
