# Generated by Django 5.2.17 on 2026-09-22 21:26

import django.db.models.deletion
import tracker.models
from decimal import Decimal
from django.conf import settings
from decimal import Decimal

from django.db import migrations, models


def backfill_net(apps, schema_editor):
    """Existing rows hold one ambiguous number. Treat it as NET (the number contracts are written in) and derive
    the gross. The two live projects were confirmed by hand on 2026-09-22 — one was net, one was gross — and
    the gross one is corrected right after this runs (see the deploy notes)."""
    Project = apps.get_model("tracker", "Project")
    for p in Project.objects.all():
        net = Decimal(p.contract_value or 0)
        p.contract_value_net = net
        p.contract_value = (net * Decimal("1.075")).quantize(Decimal("0.01"))
        p.save(update_fields=["contract_value_net", "contract_value"])



class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0008_issue_attachment_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="contract_value_net",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="project",
            name="vat_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("7.50"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="vat_treatment",
            field=models.CharField(default="standard", max_length=20),
        ),
        migrations.RunPython(backfill_net, migrations.RunPython.noop),
        migrations.CreateModel(
            name="ClientInvoice",
            fields=[
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("checked", "Checked"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField()),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("check_comment", models.TextField(blank=True, null=True)),
                ("review_version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.CharField(
                        default=tracker.models.id_inv,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_number", models.CharField(max_length=40)),
                ("issued_at", models.DateField()),
                ("description", models.CharField(blank=True, max_length=300)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "vat_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("receipts", models.JSONField(blank=True, default=list)),
                ("vat_status", models.CharField(default="outstanding", max_length=20)),
                ("vat_settled_at", models.DateField(blank=True, null=True)),
                ("vat_note", models.CharField(blank=True, max_length=300, null=True)),
                ("vat_evidence_ids", models.JSONField(blank=True, default=list)),
                ("attachment_ids", models.JSONField(blank=True, default=list)),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="client_invoices",
                        to="tracker.project",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vat_settled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "invoice_number"),
                        name="uniq_invoice_number_per_project",
                    )
                ],
            },
        ),
    ]
