# Generated by Django 5.2.17 on 2026-09-23 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def existing_contracts_are_received(apps, schema_editor):
    """Every project that exists today has its contract in hand — the draft state is for projects opened from now on."""
    Project = apps.get_model("tracker", "Project")
    Project.objects.filter(contract_value_net__gt=0).update(contract_status="received")



class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0010_vat_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="contract_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="tracker.document",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="contract_received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="contract_received_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="contract_status",
            field=models.CharField(default="draft", max_length=10),
        ),
            migrations.RunPython(existing_contracts_are_received, migrations.RunPython.noop),
    ]
